#!/usr/bin/env bash
# writing script to automate nginx on web-01(server)

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World' > /var/www/html/index.nginx-debian.html
sudo service nginx start
