#!/usr/bin/env bash
# sets up a new 404 error page
sudo apt-get update
sudo apt-get upgrade -y
sudo apt install haproxy -y
sudo echo "ENABLED=1" >> /etc/default/haproxy
sudo echo "frontend http_front
        bind *:80
        stats uri /haproxy?stats
        default_backend http_back

backend http_back
        balance roundrobin
        server 36917-web-01 18.232.59.75 check
        server 36917-web-02 18.234.129.64 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
